version: '3.7'

services:
    dev:
        container_name: api_dev
        image: api_dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: sh -c "npm install ; npm run start:debug"

        ports:
            - 3000:3000
            - 3001:9229
        networks:
            - nestjs-network
        depends_on:
            - mongodb
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: always

    mongodb:
        image: mongo:latest
        container_name: mongodb
        volumes:
            - ./database:/data/db
        ports:
            - 27017:27017
        networks:
            - nestjs-network
        restart: always

    prod:
        container_name: api_prod
        image: api_prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: sh -c "npm install ; npm run start:prod"
        ports:
            - 8001:8001
            - 9229:9230
        networks:
            - nestjs-network
        depends_on:
            - mongodb
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
networks:
    nestjs-network:
        driver: bridge
